# Site settings
name: Argost's Home
email: cambriayang@qq.com
author: Cambria Yang
url: https://ayeio.com
resume_site: http:/cambriayang/
github: https://github.com/cambriayang
baseurl: "/ayeio"
description: Actually, less is more!
meta_description: 叶林萧;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: cambriayang

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

